/**
 * Design Tokens Import - Generated by Style Dictionary
 *
 * This file re-exports design tokens organized by mode (light/dark)
 * for easier consumption in theme.ts
 *
 * @since 0.12.0 - Complete migration to generated tokens (no more theme.json dependency)
 */

import * as tokens from '../tokens/generated/ts/tokens';

// ============================================================================
// TYPOGRAPHY TOKENS
// ============================================================================
export const typographyTokens = {
  fontFamily: tokens.PrimitivesTypographyFontFamilyStack,
  fontSize: 16, // base font size in pixels (from 1rem)
  fontWeightLight: Number(tokens.PrimitivesTypographyFontWeightLight),
  fontWeightRegular: Number(tokens.PrimitivesTypographyFontWeightRegular),
  fontWeightMedium: Number(tokens.PrimitivesTypographyFontWeightMedium),
  fontWeightSemiBold: Number(tokens.PrimitivesTypographyFontWeightSemibold),
  fontWeightBold: Number(tokens.PrimitivesTypographyFontWeightBold),
  // Typography variants (MUI compatible)
  h1: {
    fontFamily: tokens.PrimitivesTypographyFontFamilyStack,
    fontWeight: Number(tokens.PrimitivesTypographyFontWeightSemibold),
    fontSize: tokens.PrimitivesTypographyFontSize4xl, // 3.75rem (60px)
    lineHeight: Number(tokens.PrimitivesTypographyLineHeightTight), // 1.2
    letterSpacing: '-0.01562em',
  },
  h2: {
    fontFamily: tokens.PrimitivesTypographyFontFamilyStack,
    fontWeight: Number(tokens.PrimitivesTypographyFontWeightSemibold),
    fontSize: tokens.PrimitivesTypographyFontSize3xl, // 3rem (48px)
    lineHeight: Number(tokens.PrimitivesTypographyLineHeightTight), // 1.2
    letterSpacing: '-0.00833em',
  },
  h3: {
    fontFamily: tokens.PrimitivesTypographyFontFamilyStack,
    fontWeight: Number(tokens.PrimitivesTypographyFontWeightSemibold),
    fontSize: tokens.PrimitivesTypographyFontSize2xl, // 2.125rem (34px)
    lineHeight: Number(tokens.PrimitivesTypographyLineHeightTight), // 1.2
    letterSpacing: '0em',
  },
  h4: {
    fontFamily: tokens.PrimitivesTypographyFontFamilyStack,
    fontWeight: Number(tokens.PrimitivesTypographyFontWeightSemibold),
    fontSize: tokens.PrimitivesTypographyFontSizeXl, // 1.5rem (24px)
    lineHeight: Number(tokens.PrimitivesTypographyLineHeightTight), // 1.2
    letterSpacing: '0.00735em',
  },
  h5: {
    fontFamily: tokens.PrimitivesTypographyFontFamilyStack,
    fontWeight: Number(tokens.PrimitivesTypographyFontWeightSemibold),
    fontSize: tokens.PrimitivesTypographyFontSizeLg, // 1.25rem (20px)
    lineHeight: Number(tokens.PrimitivesTypographyLineHeightTight), // 1.2
    letterSpacing: '0em',
  },
  h6: {
    fontFamily: tokens.PrimitivesTypographyFontFamilyStack,
    fontWeight: Number(tokens.PrimitivesTypographyFontWeightSemibold),
    fontSize: tokens.PrimitivesTypographyFontSizeMd, // 1rem (16px)
    lineHeight: Number(tokens.PrimitivesTypographyLineHeightTight), // 1.2
    letterSpacing: '0.0075em',
  },
  body1: {
    fontFamily: tokens.PrimitivesTypographyFontFamilyStack,
    fontWeight: Number(tokens.PrimitivesTypographyFontWeightRegular),
    fontSize: tokens.PrimitivesTypographyFontSizeMd, // 1rem (16px)
    lineHeight: Number(tokens.PrimitivesTypographyLineHeightNormal), // 1.5
    letterSpacing: '0.00938em',
  },
  body2: {
    fontFamily: tokens.PrimitivesTypographyFontFamilyStack,
    fontWeight: Number(tokens.PrimitivesTypographyFontWeightRegular),
    fontSize: tokens.PrimitivesTypographyFontSizeSm, // 0.875rem (14px)
    lineHeight: Number(tokens.PrimitivesTypographyLineHeightSnug), // 1.43
    letterSpacing: '0.01071em',
  },
  subtitle1: {
    fontFamily: tokens.PrimitivesTypographyFontFamilyStack,
    fontWeight: Number(tokens.PrimitivesTypographyFontWeightMedium),
    fontSize: tokens.PrimitivesTypographyFontSizeMd, // 1rem (16px)
    lineHeight: Number(tokens.PrimitivesTypographyLineHeightLoose), // 1.75
    letterSpacing: '0.00938em',
  },
  subtitle2: {
    fontFamily: tokens.PrimitivesTypographyFontFamilyStack,
    fontWeight: Number(tokens.PrimitivesTypographyFontWeightMedium),
    fontSize: tokens.PrimitivesTypographyFontSizeSm, // 0.875rem (14px)
    lineHeight: 1.57,
    letterSpacing: '0.00714em',
  },
  button: {
    fontFamily: tokens.PrimitivesTypographyFontFamilyStack,
    fontWeight: Number(tokens.PrimitivesTypographyFontWeightSemibold),
    fontSize: tokens.PrimitivesTypographyFontSizeSm, // 0.875rem (14px)
    lineHeight: Number(tokens.PrimitivesTypographyLineHeightLoose), // 1.75
    letterSpacing: '0.02857em',
    textTransform: 'none' as const,
  },
  caption: {
    fontFamily: tokens.PrimitivesTypographyFontFamilyStack,
    fontWeight: Number(tokens.PrimitivesTypographyFontWeightRegular),
    fontSize: tokens.PrimitivesTypographyFontSizeXs, // 0.75rem (12px)
    lineHeight: Number(tokens.PrimitivesTypographyLineHeightRelaxed), // 1.66
    letterSpacing: '0.03333em',
  },
  overline: {
    fontFamily: tokens.PrimitivesTypographyFontFamilyStack,
    fontWeight: Number(tokens.PrimitivesTypographyFontWeightRegular),
    fontSize: tokens.PrimitivesTypographyFontSizeXs, // 0.75rem (12px)
    lineHeight: 2.66,
    letterSpacing: '0.08333em',
    textTransform: 'uppercase' as const,
  },
};

// ============================================================================
// SHAPE TOKENS (Border Radius)
// ============================================================================
export const shapeTokens = {
  borderRadius: 8, // default MUI border radius (maps to md)
  sm: 4,
  md: 8,
  lg: 12,
  xl: 20,
  rounded: 9999, // pill shape
};

// ============================================================================
// SPACING TOKENS
// ============================================================================
// Note: MUI uses a spacing function that multiplies by 8
// We provide the raw array for compatibility
export const spacingArray = [0, 4, 8, 12, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96];

// ============================================================================
// LIGHT MODE TOKENS
// ============================================================================
export const lightTokens = {
  colors: {
    primary: {
      main: tokens.SemanticColorLightPrimaryMain,
      dark: tokens.SemanticColorLightPrimaryDark,
      light: tokens.SemanticColorLightPrimaryLight,
      contrastText: tokens.SemanticColorLightPrimaryContrastText,
    },
    secondary: {
      main: tokens.SemanticColorLightSecondaryMain,
      dark: tokens.SemanticColorLightSecondaryDark,
      light: tokens.SemanticColorLightSecondaryLight,
      contrastText: tokens.SemanticColorLightSecondaryContrastText,
    },
    error: {
      main: tokens.SemanticColorLightErrorMain,
      dark: tokens.SemanticColorLightErrorDark,
      light: tokens.SemanticColorLightErrorLight,
      contrastText: tokens.SemanticColorLightErrorContrastText,
    },
    warning: {
      main: tokens.SemanticColorLightWarningMain,
      dark: tokens.SemanticColorLightWarningDark,
      light: tokens.SemanticColorLightWarningLight,
      contrastText: tokens.SemanticColorLightWarningContrastText,
    },
    info: {
      main: tokens.SemanticColorLightInfoMain,
      dark: tokens.SemanticColorLightInfoDark,
      light: tokens.SemanticColorLightInfoLight,
      contrastText: tokens.SemanticColorLightInfoContrastText,
    },
    success: {
      main: tokens.SemanticColorLightSuccessMain,
      dark: tokens.SemanticColorLightSuccessDark,
      light: tokens.SemanticColorLightSuccessLight,
      contrastText: tokens.SemanticColorLightSuccessContrastText,
    },
    background: {
      default: tokens.SemanticColorLightBackgroundDefault,
      paper: tokens.SemanticColorLightBackgroundPaper,
    },
    text: {
      primary: tokens.SemanticColorLightTextPrimary,
      secondary: tokens.SemanticColorLightTextSecondary,
      disabled: tokens.SemanticColorLightTextDisabled,
    },
    action: {
      active: tokens.SemanticColorLightActionActive,
      hover: tokens.SemanticColorLightActionHover,
      selected: tokens.SemanticColorLightActionSelected,
      disabled: tokens.SemanticColorLightActionDisabled,
      disabledBackground: tokens.SemanticColorLightActionDisabledBackground,
    },
    divider: tokens.SemanticColorLightDivider,
    primitives: {
      brand: {
        verones: {
          main: tokens.PrimitivesColorsBrandVerones,
          50: '#E6F5F5',
          100: '#B3E0E2',
          200: '#82CCD0',
          300: '#4EB8BB',
          400: '#1AA3A3',
          500: '#009999',
          600: '#008C8B',
          700: '#00686f',
          800: '#004e53',
        },
        lima: tokens.PrimitivesColorsBrandLima,
      },
      neutral: {
        white: tokens.PrimitivesColorsNeutralWhite,
        black: tokens.PrimitivesColorsNeutralBlack,
        gray: {
          50: tokens.PrimitivesColorsNeutralGray50,
          100: tokens.PrimitivesColorsNeutralGray100,
          200: tokens.PrimitivesColorsNeutralGray200,
          300: tokens.PrimitivesColorsNeutralGray300,
          400: tokens.PrimitivesColorsNeutralGray400,
          500: tokens.PrimitivesColorsNeutralGray500,
          600: tokens.PrimitivesColorsNeutralGray600,
          700: tokens.PrimitivesColorsNeutralGray700,
          800: tokens.PrimitivesColorsNeutralGray800,
          900: tokens.PrimitivesColorsNeutralGray900,
        },
      },
      status: {
        error: {
          50: tokens.PrimitivesColorsStatusError50,
          100: tokens.PrimitivesColorsStatusError100,
          500: tokens.PrimitivesColorsStatusError500,
          600: tokens.PrimitivesColorsStatusError600,
          700: tokens.PrimitivesColorsStatusError700,
        },
        warning: {
          50: tokens.PrimitivesColorsStatusWarning50,
          500: tokens.PrimitivesColorsStatusWarning500,
          600: tokens.PrimitivesColorsStatusWarning600,
          700: tokens.PrimitivesColorsStatusWarning700,
        },
        info: {
          50: tokens.PrimitivesColorsStatusInfo50,
          100: tokens.PrimitivesColorsStatusInfo100,
          500: tokens.PrimitivesColorsStatusInfo500,
          600: tokens.PrimitivesColorsStatusInfo600,
          700: tokens.PrimitivesColorsStatusInfo700,
          800: tokens.PrimitivesColorsStatusInfo800,
        },
        success: {
          50: tokens.PrimitivesColorsStatusSuccess50,
          100: tokens.PrimitivesColorsStatusSuccess100,
          500: tokens.PrimitivesColorsStatusSuccess500,
          600: tokens.PrimitivesColorsStatusSuccess600,
          700: tokens.PrimitivesColorsStatusSuccess700,
          800: tokens.PrimitivesColorsStatusSuccess800,
        },
      },
      alpha: {
        black: {
          4: tokens.PrimitivesColorsAlphaBlack4,
          8: tokens.PrimitivesColorsAlphaBlack8,
          12: tokens.PrimitivesColorsAlphaBlack12,
          23: tokens.PrimitivesColorsAlphaBlack23,
          26: tokens.PrimitivesColorsAlphaBlack26,
          38: tokens.PrimitivesColorsAlphaBlack38,
          42: tokens.PrimitivesColorsAlphaBlack42,
          56: tokens.PrimitivesColorsAlphaBlack56,
          60: tokens.PrimitivesColorsAlphaBlack60,
          87: tokens.PrimitivesColorsAlphaBlack87,
        },
        white: {
          8: tokens.PrimitivesColorsAlphaWhite8,
          12: tokens.PrimitivesColorsAlphaWhite12,
          16: tokens.PrimitivesColorsAlphaWhite16,
          23: tokens.PrimitivesColorsAlphaWhite23,
          26: tokens.PrimitivesColorsAlphaWhite26,
          30: tokens.PrimitivesColorsAlphaWhite30,
          42: tokens.PrimitivesColorsAlphaWhite42,
          50: tokens.PrimitivesColorsAlphaWhite50,
          70: tokens.PrimitivesColorsAlphaWhite70,
          100: tokens.PrimitivesColorsAlphaWhite100,
        },
        primary: {
          8: tokens.PrimitivesColorsAlphaPrimary8,
          12: tokens.PrimitivesColorsAlphaPrimary12,
          16: tokens.PrimitivesColorsAlphaPrimary16,
          25: tokens.PrimitivesColorsAlphaPrimary25,
          '24-dark': tokens.PrimitivesColorsAlphaPrimary24Dark,
          '32-dark': tokens.PrimitivesColorsAlphaPrimary32Dark,
          '40-dark': tokens.PrimitivesColorsAlphaPrimary40Dark,
        },
      },
      special: {
        rating: tokens.PrimitivesColorsSpecialRating,
      },
    },
    semantic: {
      primary: {
        main: tokens.SemanticColorLightPrimaryMain,
        dark: tokens.SemanticColorLightPrimaryDark,
        light: tokens.SemanticColorLightPrimaryLight,
        contrastText: tokens.SemanticColorLightPrimaryContrastText,
      },
      secondary: {
        main: tokens.SemanticColorLightSecondaryMain,
        dark: tokens.SemanticColorLightSecondaryDark,
        light: tokens.SemanticColorLightSecondaryLight,
        contrastText: tokens.SemanticColorLightSecondaryContrastText,
      },
      error: {
        main: tokens.SemanticColorLightErrorMain,
        dark: tokens.SemanticColorLightErrorDark,
        light: tokens.SemanticColorLightErrorLight,
        contrastText: tokens.SemanticColorLightErrorContrastText,
      },
      warning: {
        main: tokens.SemanticColorLightWarningMain,
        dark: tokens.SemanticColorLightWarningDark,
        light: tokens.SemanticColorLightWarningLight,
        contrastText: tokens.SemanticColorLightWarningContrastText,
      },
      info: {
        main: tokens.SemanticColorLightInfoMain,
        dark: tokens.SemanticColorLightInfoDark,
        light: tokens.SemanticColorLightInfoLight,
        contrastText: tokens.SemanticColorLightInfoContrastText,
      },
      success: {
        main: tokens.SemanticColorLightSuccessMain,
        dark: tokens.SemanticColorLightSuccessDark,
        light: tokens.SemanticColorLightSuccessLight,
        contrastText: tokens.SemanticColorLightSuccessContrastText,
      },
      background: {
        default: tokens.SemanticColorLightBackgroundDefault,
        paper: tokens.SemanticColorLightBackgroundPaper,
      },
      text: {
        primary: tokens.SemanticColorLightTextPrimary,
        secondary: tokens.SemanticColorLightTextSecondary,
        disabled: tokens.SemanticColorLightTextDisabled,
      },
      action: {
        active: tokens.SemanticColorLightActionActive,
        hover: tokens.SemanticColorLightActionHover,
        selected: tokens.SemanticColorLightActionSelected,
        disabled: tokens.SemanticColorLightActionDisabled,
        disabledBackground: tokens.SemanticColorLightActionDisabledBackground,
      },
      divider: tokens.SemanticColorLightDivider,
    },
  },
  components: {
    alert: {
      borderRadius: tokens.ComponentAlertLightBorderRadius,
      error: {
        filled: {
          background: tokens.ComponentAlertLightErrorFilledBackground,
          foreground: tokens.ComponentAlertLightErrorFilledForeground,
        },
        outlined: {
          background: tokens.ComponentAlertLightErrorOutlinedBackground,
          foreground: tokens.ComponentAlertLightErrorOutlinedForeground,
          border: tokens.ComponentAlertLightErrorOutlinedBorder,
        },
        standard: {
          background: tokens.ComponentAlertLightErrorStandardBackground,
          foreground: tokens.ComponentAlertLightErrorStandardForeground,
        },
      },
      warning: {
        filled: {
          background: tokens.ComponentAlertLightWarningFilledBackground,
          foreground: tokens.ComponentAlertLightWarningFilledForeground,
        },
        outlined: {
          background: tokens.ComponentAlertLightWarningOutlinedBackground,
          foreground: tokens.ComponentAlertLightWarningOutlinedForeground,
          border: tokens.ComponentAlertLightWarningOutlinedBorder,
        },
        standard: {
          background: tokens.ComponentAlertLightWarningStandardBackground,
          foreground: tokens.ComponentAlertLightWarningStandardForeground,
        },
      },
      info: {
        filled: {
          background: tokens.ComponentAlertLightInfoFilledBackground,
          foreground: tokens.ComponentAlertLightInfoFilledForeground,
        },
        outlined: {
          background: tokens.ComponentAlertLightInfoOutlinedBackground,
          foreground: tokens.ComponentAlertLightInfoOutlinedForeground,
          border: tokens.ComponentAlertLightInfoOutlinedBorder,
        },
        standard: {
          background: tokens.ComponentAlertLightInfoStandardBackground,
          foreground: tokens.ComponentAlertLightInfoStandardForeground,
        },
      },
      success: {
        filled: {
          background: tokens.ComponentAlertLightSuccessFilledBackground,
          foreground: tokens.ComponentAlertLightSuccessFilledForeground,
        },
        outlined: {
          background: tokens.ComponentAlertLightSuccessOutlinedBackground,
          foreground: tokens.ComponentAlertLightSuccessOutlinedForeground,
          border: tokens.ComponentAlertLightSuccessOutlinedBorder,
        },
        standard: {
          background: tokens.ComponentAlertLightSuccessStandardBackground,
          foreground: tokens.ComponentAlertLightSuccessStandardForeground,
        },
      },
    },
    input: {
      borderRadius: tokens.ComponentInputLightBorderRadius,
      standard: {
        enabledBorder: tokens.ComponentInputLightStandardEnabledBorder,
      },
      filled: {
        enabledFill: tokens.ComponentInputLightFilledEnabledFill,
      },
      outlined: {
        enabledBorder: tokens.ComponentInputLightOutlinedEnabledBorder,
      },
    },
    paper: {
      elevation0: tokens.ComponentPaperLightElevation0,
      elevation1: tokens.ComponentPaperLightElevation1,
      elevation2: tokens.ComponentPaperLightElevation2,
    },
    chip: {
      defaultCloseFill: tokens.ComponentChipDefaultCloseFill,
      defaultEnabledBorder: tokens.ComponentChipDefaultEnabledBorder,
    },
    button: {
      borderRadius: tokens.ComponentButtonBorderRadius,
    },
    card: {
      borderRadius: tokens.ComponentCardLightBorderRadius,
    },
    dialog: {
      borderRadius: tokens.ComponentDialogLightBorderRadius,
    },
    table: {
      border: tokens.ComponentTableLightBorder,
      header: {
        background: tokens.ComponentTableLightHeaderBackground,
      },
    },
    rating: {
      activeFill: tokens.ComponentRatingActiveFill,
      enabledBorder: tokens.ComponentRatingEnabledBorder,
    },
  },
};

// ============================================================================
// DARK MODE TOKENS
// ============================================================================
export const darkTokens = {
  colors: {
    primary: {
      main: tokens.SemanticColorDarkPrimaryMain,
      dark: tokens.SemanticColorDarkPrimaryDark,
      light: tokens.SemanticColorDarkPrimaryLight,
      contrastText: tokens.SemanticColorDarkPrimaryContrastText,
    },
    secondary: {
      main: tokens.SemanticColorDarkSecondaryMain,
      dark: tokens.SemanticColorDarkSecondaryDark,
      light: tokens.SemanticColorDarkSecondaryLight,
      contrastText: tokens.SemanticColorDarkSecondaryContrastText,
    },
    error: {
      main: tokens.SemanticColorDarkErrorMain,
      dark: tokens.SemanticColorDarkErrorDark,
      light: tokens.SemanticColorDarkErrorLight,
      contrastText: tokens.SemanticColorDarkErrorContrastText,
    },
    warning: {
      main: tokens.SemanticColorDarkWarningMain,
      dark: tokens.SemanticColorDarkWarningDark,
      light: tokens.SemanticColorDarkWarningLight,
      contrastText: tokens.SemanticColorDarkWarningContrastText,
    },
    info: {
      main: tokens.SemanticColorDarkInfoMain,
      dark: tokens.SemanticColorDarkInfoDark,
      light: tokens.SemanticColorDarkInfoLight,
      contrastText: tokens.SemanticColorDarkInfoContrastText,
    },
    success: {
      main: tokens.SemanticColorDarkSuccessMain,
      dark: tokens.SemanticColorDarkSuccessDark,
      light: tokens.SemanticColorDarkSuccessLight,
      contrastText: tokens.SemanticColorDarkSuccessContrastText,
    },
    background: {
      default: tokens.SemanticColorDarkBackgroundDefault,
      paper: tokens.SemanticColorDarkBackgroundPaper,
    },
    text: {
      primary: tokens.SemanticColorDarkTextPrimary,
      secondary: tokens.SemanticColorDarkTextSecondary,
      disabled: tokens.SemanticColorDarkTextDisabled,
    },
    action: {
      active: tokens.SemanticColorDarkActionActive,
      hover: tokens.SemanticColorDarkActionHover,
      selected: tokens.SemanticColorDarkActionSelected,
      disabled: tokens.SemanticColorDarkActionDisabled,
      disabledBackground: tokens.SemanticColorDarkActionDisabledBackground,
    },
    divider: tokens.SemanticColorDarkDivider,
  },
  components: {
    alert: {
      borderRadius: tokens.ComponentAlertDarkBorderRadius,
      error: {
        filled: {
          background: tokens.ComponentAlertDarkErrorFilledBackground,
          foreground: tokens.ComponentAlertDarkErrorFilledForeground,
        },
        outlined: {
          background: tokens.ComponentAlertDarkErrorOutlinedBackground,
          foreground: tokens.ComponentAlertDarkErrorOutlinedForeground,
          border: tokens.ComponentAlertDarkErrorOutlinedBorder,
        },
        standard: {
          background: tokens.ComponentAlertDarkErrorStandardBackground,
          foreground: tokens.ComponentAlertDarkErrorStandardForeground,
        },
      },
      warning: {
        filled: {
          background: tokens.ComponentAlertDarkWarningFilledBackground,
          foreground: tokens.ComponentAlertDarkWarningFilledForeground,
        },
        outlined: {
          background: tokens.ComponentAlertDarkWarningOutlinedBackground,
          foreground: tokens.ComponentAlertDarkWarningOutlinedForeground,
          border: tokens.ComponentAlertDarkWarningOutlinedBorder,
        },
        standard: {
          background: tokens.ComponentAlertDarkWarningStandardBackground,
          foreground: tokens.ComponentAlertDarkWarningStandardForeground,
        },
      },
      info: {
        filled: {
          background: tokens.ComponentAlertDarkInfoFilledBackground,
          foreground: tokens.ComponentAlertDarkInfoFilledForeground,
        },
        outlined: {
          background: tokens.ComponentAlertDarkInfoOutlinedBackground,
          foreground: tokens.ComponentAlertDarkInfoOutlinedForeground,
          border: tokens.ComponentAlertDarkInfoOutlinedBorder,
        },
        standard: {
          background: tokens.ComponentAlertDarkInfoStandardBackground,
          foreground: tokens.ComponentAlertDarkInfoStandardForeground,
        },
      },
      success: {
        filled: {
          background: tokens.ComponentAlertDarkSuccessFilledBackground,
          foreground: tokens.ComponentAlertDarkSuccessFilledForeground,
        },
        outlined: {
          background: tokens.ComponentAlertDarkSuccessOutlinedBackground,
          foreground: tokens.ComponentAlertDarkSuccessOutlinedForeground,
          border: tokens.ComponentAlertDarkSuccessOutlinedBorder,
        },
        standard: {
          background: tokens.ComponentAlertDarkSuccessStandardBackground,
          foreground: tokens.ComponentAlertDarkSuccessStandardForeground,
        },
      },
    },
    input: {
      borderRadius: tokens.ComponentInputDarkBorderRadius,
      standard: {
        enabledBorder: tokens.ComponentInputDarkStandardEnabledBorder,
      },
      filled: {
        enabledFill: tokens.ComponentInputDarkFilledEnabledFill,
      },
      outlined: {
        enabledBorder: tokens.ComponentInputDarkOutlinedEnabledBorder,
      },
    },
    paper: {
      elevation0: tokens.ComponentPaperDarkElevation0,
      elevation1: tokens.ComponentPaperDarkElevation1,
      elevation2: tokens.ComponentPaperDarkElevation2,
      elevation4: tokens.ComponentPaperDarkElevation4,
      elevation6: tokens.ComponentPaperDarkElevation6,
      elevation8: tokens.ComponentPaperDarkElevation8,
      elevation12: tokens.ComponentPaperDarkElevation12,
      elevation16: tokens.ComponentPaperDarkElevation16,
      elevation24: tokens.ComponentPaperDarkElevation24,
    },
    chip: {
      defaultCloseFill: tokens.PrimitivesColorsNeutralWhite,
      defaultEnabledBorder: tokens.PrimitivesColorsNeutralGray600,
    },
    button: {
      borderRadius: tokens.ComponentButtonBorderRadius,
    },
    card: {
      borderRadius: tokens.ComponentCardDarkBorderRadius,
    },
    dialog: {
      borderRadius: tokens.ComponentDialogDarkBorderRadius,
    },
    table: {
      border: tokens.ComponentTableDarkBorder,
      header: {
        background: tokens.ComponentTableDarkHeaderBackground,
      },
    },
    rating: {
      activeFill: tokens.ComponentRatingActiveFill,
      enabledBorder: tokens.PrimitivesColorsAlphaWhite30,
    },
  },
};

// ============================================================================
// SIDENAV COMPONENT TOKENS (Custom Component Tokens)
// ============================================================================
export const sidenavTokens = {
  light: {
    borderRadius: 8, // Using md shape token
    itemBackground: 'transparent',
    itemSelectedBackground: '#E3F2FD', // Light blue
    itemHoverBackground: '#F5F5F5', // Light gray
    itemIconColor: '#666666',
    itemTextColor: '#212121',
  },
  dark: {
    borderRadius: 8, // Using md shape token
    itemBackground: 'transparent',
    itemSelectedBackground: '#1A237E', // Dark blue
    itemHoverBackground: '#303030', // Dark gray
    itemIconColor: '#BDBDBD',
    itemTextColor: '#FFFFFF',
  },
};
