/**
 * Design Tokens Import - Generated by Style Dictionary
 *
 * This file re-exports design tokens organized by mode (light/dark)
 * for easier consumption in theme.ts
 */

import * as tokens from '../tokens/generated/ts/tokens';

// ============================================================================
// LIGHT MODE TOKENS
// ============================================================================
export const lightTokens = {
  colors: {
    primary: {
      main: tokens.SemanticColorPrimaryMain,
      dark: tokens.SemanticColorPrimaryDark,
      light: tokens.SemanticColorPrimaryLight,
      contrastText: tokens.SemanticColorPrimaryContrastText,
    },
    secondary: {
      main: tokens.SemanticColorSecondaryMain,
      dark: tokens.SemanticColorSecondaryDark,
      light: tokens.SemanticColorSecondaryLight,
      contrastText: tokens.SemanticColorSecondaryContrastText,
    },
    error: {
      main: tokens.SemanticColorErrorMain,
      dark: tokens.SemanticColorErrorDark,
      light: tokens.SemanticColorErrorLight,
      contrastText: tokens.SemanticColorErrorContrastText,
    },
    warning: {
      main: tokens.SemanticColorWarningMain,
      dark: tokens.SemanticColorWarningDark,
      light: tokens.SemanticColorWarningLight,
      contrastText: tokens.SemanticColorWarningContrastText,
    },
    info: {
      main: tokens.SemanticColorInfoMain,
      dark: tokens.SemanticColorInfoDark,
      light: tokens.SemanticColorInfoLight,
      contrastText: tokens.SemanticColorInfoContrastText,
    },
    success: {
      main: tokens.SemanticColorSuccessMain,
      dark: tokens.SemanticColorSuccessDark,
      light: tokens.SemanticColorSuccessLight,
      contrastText: tokens.SemanticColorSuccessContrastText,
    },
    background: {
      default: tokens.SemanticColorBackgroundDefault,
      paper: tokens.SemanticColorBackgroundPaper,
    },
    text: {
      primary: tokens.SemanticColorTextPrimary,
      secondary: tokens.SemanticColorTextSecondary,
      disabled: tokens.SemanticColorTextDisabled,
    },
    action: {
      active: tokens.SemanticColorActionActive,
      hover: tokens.SemanticColorActionHover,
      selected: tokens.SemanticColorActionSelected,
      disabled: tokens.SemanticColorActionDisabled,
      disabledBackground: tokens.SemanticColorActionDisabledBackground,
    },
    divider: tokens.SemanticColorDivider,
  },
  components: {
    alert: {
      borderRadius: tokens.ComponentAlertBorderRadius,
      error: {
        filled: {
          background: tokens.ComponentAlertErrorFilledBackground,
          foreground: tokens.ComponentAlertErrorFilledForeground,
        },
        outlined: {
          background: tokens.ComponentAlertErrorOutlinedBackground,
          foreground: tokens.ComponentAlertErrorOutlinedForeground,
          border: tokens.ComponentAlertErrorOutlinedBorder,
        },
        standard: {
          background: tokens.ComponentAlertErrorStandardBackground,
          foreground: tokens.ComponentAlertErrorStandardForeground,
        },
      },
      warning: {
        filled: {
          background: tokens.ComponentAlertWarningFilledBackground,
          foreground: tokens.ComponentAlertWarningFilledForeground,
        },
        outlined: {
          background: tokens.ComponentAlertWarningOutlinedBackground,
          foreground: tokens.ComponentAlertWarningOutlinedForeground,
          border: tokens.ComponentAlertWarningOutlinedBorder,
        },
        standard: {
          background: tokens.ComponentAlertWarningStandardBackground,
          foreground: tokens.ComponentAlertWarningStandardForeground,
        },
      },
      info: {
        filled: {
          background: tokens.ComponentAlertInfoFilledBackground,
          foreground: tokens.ComponentAlertInfoFilledForeground,
        },
        outlined: {
          background: tokens.ComponentAlertInfoOutlinedBackground,
          foreground: tokens.ComponentAlertInfoOutlinedForeground,
          border: tokens.ComponentAlertInfoOutlinedBorder,
        },
        standard: {
          background: tokens.ComponentAlertInfoStandardBackground,
          foreground: tokens.ComponentAlertInfoStandardForeground,
        },
      },
      success: {
        filled: {
          background: tokens.ComponentAlertSuccessFilledBackground,
          foreground: tokens.ComponentAlertSuccessFilledForeground,
        },
        outlined: {
          background: tokens.ComponentAlertSuccessOutlinedBackground,
          foreground: tokens.ComponentAlertSuccessOutlinedForeground,
          border: tokens.ComponentAlertSuccessOutlinedBorder,
        },
        standard: {
          background: tokens.ComponentAlertSuccessStandardBackground,
          foreground: tokens.ComponentAlertSuccessStandardForeground,
        },
      },
    },
    input: {
      borderRadius: tokens.ComponentInputBorderRadius,
      standard: {
        enabledBorder: tokens.ComponentInputStandardEnabledBorder,
      },
      filled: {
        enabledFill: tokens.ComponentInputFilledEnabledFill,
      },
      outlined: {
        enabledBorder: tokens.ComponentInputOutlinedEnabledBorder,
      },
    },
    paper: {
      elevation0: tokens.ComponentPaperElevation0,
      elevation1: tokens.ComponentPaperElevation1,
      elevation2: tokens.ComponentPaperElevation2,
    },
    chip: {
      defaultCloseFill: tokens.ComponentChipDefaultCloseFill,
      defaultEnabledBorder: tokens.ComponentChipDefaultEnabledBorder,
    },
    button: {
      borderRadius: tokens.ComponentButtonBorderRadius,
    },
    card: {
      borderRadius: tokens.ComponentCardBorderRadius,
    },
    dialog: {
      borderRadius: tokens.ComponentDialogBorderRadius,
    },
    table: {
      border: tokens.ComponentTableBorder,
      header: {
        background: tokens.ComponentTableHeaderBackground,
      },
    },
    rating: {
      activeFill: tokens.ComponentRatingActiveFill,
      enabledBorder: tokens.ComponentRatingEnabledBorder,
    },
  },
};

// ============================================================================
// DARK MODE TOKENS
// ============================================================================
export const darkTokens = {
  colors: {
    primary: {
      main: tokens.SemanticColorDarkPrimaryMain,
      dark: tokens.SemanticColorDarkPrimaryDark,
      light: tokens.SemanticColorDarkPrimaryLight,
      contrastText: tokens.SemanticColorDarkPrimaryContrastText,
    },
    secondary: {
      main: tokens.SemanticColorDarkSecondaryMain,
      dark: tokens.SemanticColorDarkSecondaryDark,
      light: tokens.SemanticColorDarkSecondaryLight,
      contrastText: tokens.SemanticColorDarkSecondaryContrastText,
    },
    error: {
      main: tokens.SemanticColorDarkErrorMain,
      dark: tokens.SemanticColorDarkErrorDark,
      light: tokens.SemanticColorDarkErrorLight,
      contrastText: tokens.SemanticColorDarkErrorContrastText,
    },
    warning: {
      main: tokens.SemanticColorDarkWarningMain,
      dark: tokens.SemanticColorDarkWarningDark,
      light: tokens.SemanticColorDarkWarningLight,
      contrastText: tokens.SemanticColorDarkWarningContrastText,
    },
    info: {
      main: tokens.SemanticColorDarkInfoMain,
      dark: tokens.SemanticColorDarkInfoDark,
      light: tokens.SemanticColorDarkInfoLight,
      contrastText: tokens.SemanticColorDarkInfoContrastText,
    },
    success: {
      main: tokens.SemanticColorDarkSuccessMain,
      dark: tokens.SemanticColorDarkSuccessDark,
      light: tokens.SemanticColorDarkSuccessLight,
      contrastText: tokens.SemanticColorDarkSuccessContrastText,
    },
    background: {
      default: tokens.SemanticColorDarkBackgroundDefault,
      paper: tokens.SemanticColorDarkBackgroundPaper,
    },
    text: {
      primary: tokens.SemanticColorDarkTextPrimary,
      secondary: tokens.SemanticColorDarkTextSecondary,
      disabled: tokens.SemanticColorDarkTextDisabled,
    },
    action: {
      active: tokens.SemanticColorDarkActionActive,
      hover: tokens.SemanticColorDarkActionHover,
      selected: tokens.SemanticColorDarkActionSelected,
      disabled: tokens.SemanticColorDarkActionDisabled,
      disabledBackground: tokens.SemanticColorDarkActionDisabledBackground,
    },
    divider: tokens.SemanticColorDarkDivider,
  },
  components: {
    alert: {
      borderRadius: tokens.ComponentAlertDarkBorderRadius,
      error: {
        filled: {
          background: tokens.ComponentAlertDarkErrorFilledBackground,
          foreground: tokens.ComponentAlertDarkErrorFilledForeground,
        },
        outlined: {
          background: tokens.ComponentAlertDarkErrorOutlinedBackground,
          foreground: tokens.ComponentAlertDarkErrorOutlinedForeground,
          border: tokens.ComponentAlertDarkErrorOutlinedBorder,
        },
        standard: {
          background: tokens.ComponentAlertDarkErrorStandardBackground,
          foreground: tokens.ComponentAlertDarkErrorStandardForeground,
        },
      },
      warning: {
        filled: {
          background: tokens.ComponentAlertDarkWarningFilledBackground,
          foreground: tokens.ComponentAlertDarkWarningFilledForeground,
        },
        outlined: {
          background: tokens.ComponentAlertDarkWarningOutlinedBackground,
          foreground: tokens.ComponentAlertDarkWarningOutlinedForeground,
          border: tokens.ComponentAlertDarkWarningOutlinedBorder,
        },
        standard: {
          background: tokens.ComponentAlertDarkWarningStandardBackground,
          foreground: tokens.ComponentAlertDarkWarningStandardForeground,
        },
      },
      info: {
        filled: {
          background: tokens.ComponentAlertDarkInfoFilledBackground,
          foreground: tokens.ComponentAlertDarkInfoFilledForeground,
        },
        outlined: {
          background: tokens.ComponentAlertDarkInfoOutlinedBackground,
          foreground: tokens.ComponentAlertDarkInfoOutlinedForeground,
          border: tokens.ComponentAlertDarkInfoOutlinedBorder,
        },
        standard: {
          background: tokens.ComponentAlertDarkInfoStandardBackground,
          foreground: tokens.ComponentAlertDarkInfoStandardForeground,
        },
      },
      success: {
        filled: {
          background: tokens.ComponentAlertDarkSuccessFilledBackground,
          foreground: tokens.ComponentAlertDarkSuccessFilledForeground,
        },
        outlined: {
          background: tokens.ComponentAlertDarkSuccessOutlinedBackground,
          foreground: tokens.ComponentAlertDarkSuccessOutlinedForeground,
          border: tokens.ComponentAlertDarkSuccessOutlinedBorder,
        },
        standard: {
          background: tokens.ComponentAlertDarkSuccessStandardBackground,
          foreground: tokens.ComponentAlertDarkSuccessStandardForeground,
        },
      },
    },
    input: {
      borderRadius: tokens.ComponentInputDarkBorderRadius,
      standard: {
        enabledBorder: tokens.ComponentInputDarkStandardEnabledBorder,
      },
      filled: {
        enabledFill: tokens.ComponentInputDarkFilledEnabledFill,
      },
      outlined: {
        enabledBorder: tokens.ComponentInputDarkOutlinedEnabledBorder,
      },
    },
    paper: {
      elevation0: tokens.ComponentPaperDarkElevation0,
      elevation1: tokens.ComponentPaperDarkElevation1,
      elevation2: tokens.ComponentPaperDarkElevation2,
      elevation4: tokens.ComponentPaperDarkElevation4,
      elevation6: tokens.ComponentPaperDarkElevation6,
      elevation8: tokens.ComponentPaperDarkElevation8,
      elevation12: tokens.ComponentPaperDarkElevation12,
      elevation16: tokens.ComponentPaperDarkElevation16,
      elevation24: tokens.ComponentPaperDarkElevation24,
    },
    chip: {
      defaultCloseFill: tokens.PrimitivesColorsNeutralWhite,
      defaultEnabledBorder: tokens.PrimitivesColorsNeutralGray600,
    },
    button: {
      borderRadius: tokens.ComponentButtonBorderRadius,
    },
    card: {
      borderRadius: tokens.ComponentCardDarkBorderRadius,
    },
    dialog: {
      borderRadius: tokens.ComponentDialogDarkBorderRadius,
    },
    table: {
      border: tokens.ComponentTableDarkBorder,
      header: {
        background: tokens.ComponentTableDarkHeaderBackground,
      },
    },
    rating: {
      activeFill: tokens.ComponentRatingActiveFill,
      enabledBorder: tokens.PrimitivesColorsAlphaWhite30,
    },
  },
};
