/**
 * Design Tokens Import - Generated by Style Dictionary
 *
 * This file re-exports design tokens organized by mode (light/dark)
 * for easier consumption in theme.ts
 *
 * @since 0.12.0 - Complete migration to generated tokens (no more theme.json dependency)
 */
export declare const typographyTokens: {
    fontFamily: string;
    fontSize: number;
    fontWeightLight: number;
    fontWeightRegular: number;
    fontWeightMedium: number;
    fontWeightSemiBold: number;
    fontWeightBold: number;
    h1: {
        fontFamily: string;
        fontWeight: number;
        fontSize: string;
        lineHeight: number;
        letterSpacing: string;
    };
    h2: {
        fontFamily: string;
        fontWeight: number;
        fontSize: string;
        lineHeight: number;
        letterSpacing: string;
    };
    h3: {
        fontFamily: string;
        fontWeight: number;
        fontSize: string;
        lineHeight: number;
        letterSpacing: string;
    };
    h4: {
        fontFamily: string;
        fontWeight: number;
        fontSize: string;
        lineHeight: number;
        letterSpacing: string;
    };
    h5: {
        fontFamily: string;
        fontWeight: number;
        fontSize: string;
        lineHeight: number;
        letterSpacing: string;
    };
    h6: {
        fontFamily: string;
        fontWeight: number;
        fontSize: string;
        lineHeight: number;
        letterSpacing: string;
    };
    body1: {
        fontFamily: string;
        fontWeight: number;
        fontSize: string;
        lineHeight: number;
        letterSpacing: string;
    };
    body2: {
        fontFamily: string;
        fontWeight: number;
        fontSize: string;
        lineHeight: number;
        letterSpacing: string;
    };
    subtitle1: {
        fontFamily: string;
        fontWeight: number;
        fontSize: string;
        lineHeight: number;
        letterSpacing: string;
    };
    subtitle2: {
        fontFamily: string;
        fontWeight: number;
        fontSize: string;
        lineHeight: number;
        letterSpacing: string;
    };
    button: {
        fontFamily: string;
        fontWeight: number;
        fontSize: string;
        lineHeight: number;
        letterSpacing: string;
        textTransform: "none";
    };
    caption: {
        fontFamily: string;
        fontWeight: number;
        fontSize: string;
        lineHeight: number;
        letterSpacing: string;
    };
    overline: {
        fontFamily: string;
        fontWeight: number;
        fontSize: string;
        lineHeight: number;
        letterSpacing: string;
        textTransform: "uppercase";
    };
};
export declare const shapeTokens: {
    borderRadius: number;
    sm: number;
    md: number;
    lg: number;
    xl: number;
    rounded: number;
};
export declare const spacingArray: number[];
export declare const lightTokens: {
    colors: {
        primary: {
            main: string;
            dark: string;
            light: string;
            contrastText: string;
        };
        secondary: {
            main: string;
            dark: string;
            light: string;
            contrastText: string;
        };
        error: {
            main: string;
            dark: string;
            light: string;
            contrastText: string;
        };
        warning: {
            main: string;
            dark: string;
            light: string;
            contrastText: string;
        };
        info: {
            main: string;
            dark: string;
            light: string;
            contrastText: string;
        };
        success: {
            main: string;
            dark: string;
            light: string;
            contrastText: string;
        };
        background: {
            default: string;
            paper: string;
        };
        text: {
            primary: string;
            secondary: string;
            disabled: string;
        };
        action: {
            active: string;
            hover: string;
            selected: string;
            disabled: string;
            disabledBackground: string;
        };
        divider: string;
    };
    components: {
        alert: {
            borderRadius: string;
            error: {
                filled: {
                    background: string;
                    foreground: string;
                };
                outlined: {
                    background: string;
                    foreground: string;
                    border: string;
                };
                standard: {
                    background: string;
                    foreground: string;
                };
            };
            warning: {
                filled: {
                    background: string;
                    foreground: string;
                };
                outlined: {
                    background: string;
                    foreground: string;
                    border: string;
                };
                standard: {
                    background: string;
                    foreground: string;
                };
            };
            info: {
                filled: {
                    background: string;
                    foreground: string;
                };
                outlined: {
                    background: string;
                    foreground: string;
                    border: string;
                };
                standard: {
                    background: string;
                    foreground: string;
                };
            };
            success: {
                filled: {
                    background: string;
                    foreground: string;
                };
                outlined: {
                    background: string;
                    foreground: string;
                    border: string;
                };
                standard: {
                    background: string;
                    foreground: string;
                };
            };
        };
        input: {
            borderRadius: string;
            standard: {
                enabledBorder: string;
            };
            filled: {
                enabledFill: string;
            };
            outlined: {
                enabledBorder: string;
            };
        };
        paper: {
            elevation0: string;
            elevation1: string;
            elevation2: string;
        };
        chip: {
            defaultCloseFill: string;
            defaultEnabledBorder: string;
        };
        button: {
            borderRadius: string;
        };
        card: {
            borderRadius: string;
        };
        dialog: {
            borderRadius: string;
        };
        table: {
            border: string;
            header: {
                background: string;
            };
        };
        rating: {
            activeFill: string;
            enabledBorder: string;
        };
    };
};
export declare const darkTokens: {
    colors: {
        primary: {
            main: string;
            dark: string;
            light: string;
            contrastText: string;
        };
        secondary: {
            main: string;
            dark: string;
            light: string;
            contrastText: string;
        };
        error: {
            main: string;
            dark: string;
            light: string;
            contrastText: string;
        };
        warning: {
            main: string;
            dark: string;
            light: string;
            contrastText: string;
        };
        info: {
            main: string;
            dark: string;
            light: string;
            contrastText: string;
        };
        success: {
            main: string;
            dark: string;
            light: string;
            contrastText: string;
        };
        background: {
            default: string;
            paper: string;
        };
        text: {
            primary: string;
            secondary: string;
            disabled: string;
        };
        action: {
            active: string;
            hover: string;
            selected: string;
            disabled: string;
            disabledBackground: string;
        };
        divider: string;
    };
    components: {
        alert: {
            borderRadius: string;
            error: {
                filled: {
                    background: string;
                    foreground: string;
                };
                outlined: {
                    background: string;
                    foreground: string;
                    border: string;
                };
                standard: {
                    background: string;
                    foreground: string;
                };
            };
            warning: {
                filled: {
                    background: string;
                    foreground: string;
                };
                outlined: {
                    background: string;
                    foreground: string;
                    border: string;
                };
                standard: {
                    background: string;
                    foreground: string;
                };
            };
            info: {
                filled: {
                    background: string;
                    foreground: string;
                };
                outlined: {
                    background: string;
                    foreground: string;
                    border: string;
                };
                standard: {
                    background: string;
                    foreground: string;
                };
            };
            success: {
                filled: {
                    background: string;
                    foreground: string;
                };
                outlined: {
                    background: string;
                    foreground: string;
                    border: string;
                };
                standard: {
                    background: string;
                    foreground: string;
                };
            };
        };
        input: {
            borderRadius: string;
            standard: {
                enabledBorder: string;
            };
            filled: {
                enabledFill: string;
            };
            outlined: {
                enabledBorder: string;
            };
        };
        paper: {
            elevation0: string;
            elevation1: string;
            elevation2: string;
            elevation4: string;
            elevation6: string;
            elevation8: string;
            elevation12: string;
            elevation16: string;
            elevation24: string;
        };
        chip: {
            defaultCloseFill: string;
            defaultEnabledBorder: string;
        };
        button: {
            borderRadius: string;
        };
        card: {
            borderRadius: string;
        };
        dialog: {
            borderRadius: string;
        };
        table: {
            border: string;
            header: {
                background: string;
            };
        };
        rating: {
            activeFill: string;
            enabledBorder: string;
        };
    };
};
export declare const sidenavTokens: {
    light: {
        borderRadius: number;
        itemBackground: string;
        itemSelectedBackground: string;
        itemHoverBackground: string;
        itemIconColor: string;
        itemTextColor: string;
    };
    dark: {
        borderRadius: number;
        itemBackground: string;
        itemSelectedBackground: string;
        itemHoverBackground: string;
        itemIconColor: string;
        itemTextColor: string;
    };
};
//# sourceMappingURL=tokens-import.d.ts.map